#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vino
Version  : 3.22.0
Release  : 1
URL      : https://download.gnome.org/sources/vino/3.22/vino-3.22.0.tar.xz
Source0  : https://download.gnome.org/sources/vino/3.22/vino-3.22.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: vino-config
Requires: vino-bin
Requires: vino-data
Requires: vino-locales
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk+-x11-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(systemd)
BuildRequires : sed

%description
Vino
====
This package is free software and is part of the GNOME project.
The package contains an integrated VNC server for GNOME.

%package bin
Summary: bin components for the vino package.
Group: Binaries
Requires: vino-data
Requires: vino-config

%description bin
bin components for the vino package.


%package config
Summary: config components for the vino package.
Group: Default

%description config
config components for the vino package.


%package data
Summary: data components for the vino package.
Group: Data

%description data
data components for the vino package.


%package locales
Summary: locales components for the vino package.
Group: Default

%description locales
locales components for the vino package.


%prep
%setup -q -n vino-3.22.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1519074388
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1519074388
rm -rf %{buildroot}
%make_install
%find_lang vino

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/libexec/vino-server

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/user/vino-server.service

%files data
%defattr(-,root,root,-)
/usr/share/applications/vino-server.desktop
/usr/share/dbus-1/services/org.freedesktop.Telepathy.Client.Vino.service
/usr/share/glib-2.0/schemas/org.gnome.Vino.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.Vino.gschema.xml

%files locales -f vino.lang
%defattr(-,root,root,-)

