#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vino
Version  : 3.22.0
Release  : 5
URL      : https://download.gnome.org/sources/vino/3.22/vino-3.22.0.tar.xz
Source0  : https://download.gnome.org/sources/vino/3.22/vino-3.22.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: vino-data = %{version}-%{release}
Requires: vino-libexec = %{version}-%{release}
Requires: vino-license = %{version}-%{release}
Requires: vino-locales = %{version}-%{release}
Requires: vino-services = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : libgcrypt-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk+-x11-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(systemd)
BuildRequires : sed

%description
Vino
====
This package is free software and is part of the GNOME project.
The package contains an integrated VNC server for GNOME.

%package data
Summary: data components for the vino package.
Group: Data

%description data
data components for the vino package.


%package libexec
Summary: libexec components for the vino package.
Group: Default
Requires: vino-license = %{version}-%{release}

%description libexec
libexec components for the vino package.


%package license
Summary: license components for the vino package.
Group: Default

%description license
license components for the vino package.


%package locales
Summary: locales components for the vino package.
Group: Default

%description locales
locales components for the vino package.


%package services
Summary: services components for the vino package.
Group: Systemd services

%description services
services components for the vino package.


%prep
%setup -q -n vino-3.22.0
cd %{_builddir}/vino-3.22.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586244783
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1586244783
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/vino
cp %{_builddir}/vino-3.22.0/COPYING %{buildroot}/usr/share/package-licenses/vino/dfac199a7539a404407098a2541b9482279f690d
cp %{_builddir}/vino-3.22.0/server/miniupnp/LICENCE %{buildroot}/usr/share/package-licenses/vino/dff9d0f045e6aab4eb0ac806797d1f5bb9df2af0
%make_install
%find_lang vino

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/applications/vino-server.desktop
/usr/share/dbus-1/services/org.freedesktop.Telepathy.Client.Vino.service
/usr/share/glib-2.0/schemas/org.gnome.Vino.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.Vino.gschema.xml

%files libexec
%defattr(-,root,root,-)
/usr/libexec/vino-server

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/vino/dfac199a7539a404407098a2541b9482279f690d
/usr/share/package-licenses/vino/dff9d0f045e6aab4eb0ac806797d1f5bb9df2af0

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/vino-server.service

%files locales -f vino.lang
%defattr(-,root,root,-)

